spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: config-service
  cloud:
    config:
      server:
        encrypt:
          enabled: true
        git:
          default-label: main
          uri: https://github.com/Mahzarasua/ConfigServerRepo
          search-paths: config-data
          label: main
server:
  port: 8888
management:
  health:
    probes:
      enabled: true
    db:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /admin
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  app:
    version: 0.0.1-SNAPSHOT
    name: skills-api
    description: This is a REST service to manage Skills attached to a Resume
    license:
      name: "MIT License"
      url: "https://opensource.org/licenses/MIT"
    contact:
      name: "Miguel Hernandez"
      url: "https://github.com/mahzarasua"
      email: "mahzarasua@hotmail.com"
eureka:
  instance:
    statusPageUrlPath: ${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${management.endpoints.web.base-path}/health
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
encrypt:
  key: Rg#k7JyV92'7