info:
  app:
    version: 0.0.1-SNAPSHOT
    name: skills-api
    description: This is a REST service to manage Skills attached to a Resume
    spring-cloud-version: 2021.0.2
    spring-boot-version: 2.6.4
    open-api-specification-version: 2.2.0
    healthcheck: ${management.endpoints.web.base-path}/health
logging:
  level:
    com:
      mahzarasua: DEBUG
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: skills-api
  security:
    user:
      name: ${username}
      password: ${password}
eureka:
  instance:
    statusPageUrlPath: ${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${management.endpoints.web.base-path}/health
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka